def camelcase(string: str): str
def capitalcase(string: str): str
def constcase(string: str): str
def lowercase(string: str): str
def pascalcase(string: str): str
def pathcase(string: str): str
def backslashcase(string: str): str
def sentencecase(string: str): str
def snakecase(string: str): str
def spinalcase(string: str): str
def dotcase(string: str): str
def titlecase(string: str): str
def trimcase(string: str): str
def uppercase(string: str): str
def alphanumcase(string: str): str
